#!/usr/bin/env bash
#  script that transfers a file from our client to a server:
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
path_to_file=$1
ip_of_server=$2
username=$3
path_ssh_private_key=$4
scp -i "$path_ssh_private_key" -o StrictHostKeyChecking=no "$path_to_file" "$username"@"$ip_of_server":~/
