#!/usr/bin/env bash
# script that installs nginx on my web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i 's/listen  .*/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart
