#!/usr/bin/env bash
# script that installs nginx on my web server
sudo pt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
