#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="location \/ {\n\t\ttry_files \$uri \$uri\/ =404;\n\t\trewrite ^\/redirect_me https:\/\/holbnyakundi.tech permanent;\n\t}"
sudo sed -i "s|location \/ {|$string_for_replacement|" /etc/nginx/sites-enabled/default
service nginx restart
