#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server.

sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get install haproxy -y
load_balancer_config_file="/etc/haproxy/haproxy.cfg"
echo "
frontend web-frontend
    mode http
    bind *:80
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server 531456-web-01 100.25.170.102:80 check
    server 531456-web-02 100.24.236.169:80 check

" | sudo tee -a $load_balancer_config_file
echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo service haproxy start
