#!/usr/bin/env bash
# Debugging making sure Nginx is listening on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
