#!/usr/bin/env bash
# Displays a list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy
# displays lines containing the bash word

ps aux | grep bash
