#!/usr/bin/env bash
# Script that displays Best School 10 times.
count=10

while [ $count -ge 1 ]
do
       	if [ $count -eq 2 ]
		        then
				        echo "Best School"
					        echo "Hi"
						    else
							            echo "Best School"
								        fi
									    ((count--))
								    done
