#!/usr/bin/env bash
# displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# Must use the "for loop"

list="$(ls)"
for i in $list
do
	cut -d "-" -f 2- <<< "$i";
done
