#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.

sudo cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts